# Site settings
title: NIEM
# Start with excludes that are as general as is reasonable, and we can make them
# more specific when things don't get exported
# keep this listed sorted alphabetically
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/Font-Awesome/src
  - vendor/bootstrap/docs
  - "*/aspell-exceptions.txt"
  - "*/Makefile"
  - "*.dot"
  - technical/country-codes/schema.png
  - technical/json/guidance/aux
  - technical/json/guidance/tmp

gems:
  - jekyll-mentions
  - jekyll-github-metadata

# Site data
superhero_iepd_path: https://github.com/NIEM/Developer-Network-IEPD-Series--SuperHero
submit_feedback_link: https://github.com/NIEM/NIEM.github.io/issues
niem_comments_link: mailto:niem-comments@lists.gatech.edu

# origin https://github.com/mkindl/NIEM.github.io.git

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

